FROM ubuntu:latest
MAINTAINER darwinsubarmaniam@googlemail.com
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y \nginx \git
RUN apt-get install -y \php \php-fpm \php-mysql
RUN apt-get install -y \mariadb-server \mariadb-client

