FROM ubuntu:latest
MAINTAINER darwinsubarmaniam@googlemail.com
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y \nginx \git
RUN cd /home
RUN git clone https://darwinsubramaniam@gitlab.com/vcloudex/serverconfig.git
RUN cd serverconfig/Master_Site-enabled


